---
version: v3
description: covid_trace
removeTempFiles: false
clientSettings:
  retry: 3
  concurrency: 1 #number of graph clients
  channelBufferSize: 8
  space: covid_trace
  connection:
    user: root
    password: nebula
    address: graphd:9669
  postStart:
    commands: |
      CREATE SPACE IF NOT EXISTS covid_trace (partition_num=5, replica_factor=1, vid_type=FIXED_STRING(32));

      CREATE TAG IF NOT EXISTS 人(name string NOT NULL, is_confirmed bool NOT NULL);
      CREATE TAG IF NOT EXISTS 联系方式(num int NOT NULL);
      CREATE TAG IF NOT EXISTS 地址(name string NOT NULL);
      CREATE TAG IF NOT EXISTS 街道(name string NOT NULL);
      CREATE TAG IF NOT EXISTS 村镇(name string NOT NULL);
      CREATE TAG IF NOT EXISTS 行政区(name string NOT NULL);
      CREATE TAG IF NOT EXISTS 城市(name string NOT NULL);
      CREATE TAG IF NOT EXISTS 省份(name string NOT NULL);

      CREATE EDGE 同住(start_time float, end_time float);
      CREATE EDGE 到访(start_time float, end_time float);
      CREATE EDGE 属于();
      CREATE EDGE 住址();
      USE covid_trace;
    afterPeriod: 8s
logPath: ./err/covid-trace.log
files:
  - path: ./data/address.csv
    failDataPath: ./err/address.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 地址
            props:
              - name: name
                type: string
                index: 1

  - path: ./data/city.csv
    failDataPath: ./err/city.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 城市
            props:
              - name: name
                type: string
                index: 1

  - path: ./data/person.csv
    failDataPath: ./err/person.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 人
            props:
              - name: name
                type: string
                index: 1
              - name: is_confirmed
                type: bool
                index: 2

  - path: ./data/district.csv
    failDataPath: ./err/district.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 行政区
            props:
              - name: name
                type: string
                index: 1

  - path: ./data/street.csv
    failDataPath: ./err/street.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 街道
            props:
              - name: name
                type: string
                index: 2

  - path: ./data/town.csv
    failDataPath: ./err/town.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 村镇
            props:
              - name: name
                type: string
                index: 1
  - path: ./data/province.csv
    failDataPath: ./err/province.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: vertex
      vertex:
        vid:
          index: 0
        tags:
          - name: 省份
            props:
              - name: name
                type: string
                index: 1

  - path: ./data/person_livewith.csv
    failDataPath: ./err/person_livewith.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 同住
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 1
        props:
          - name: start_time
            type: float
            index: 2
          - name: end_time
            type: float
            index: 3


  - path: ./data/person_visit.csv
    failDataPath: ./err/person_visit.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 到访
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 1
        props:
          - name: start_time
            type: float
            index: 2
          - name: end_time
            type: float
            index: 3
  - path: ./data/address.csv
    failDataPath: ./err/belong_to.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 属于
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 2

  - path: ./data/street.csv
    failDataPath: ./err/belong_to.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 属于
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 3

  - path: ./data/town.csv
    failDataPath: ./err/belong_to.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 属于
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 2

  - path: ./data/district.csv
    failDataPath: ./err/belong_to.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 属于
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 2
  - path: ./data/city.csv
    failDataPath: ./err/belong_to.csv
    batchSize: 2000
    inOrder: false
    type: csv
    csv:
      withHeader: false
      withLabel: false
    schema:
      type: edge
      edge:
        name: 属于
        withRanking: false
        srcVID:
          index: 0
        dstVID:
          index: 2
